config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :topics

  get '/show' => 'line_users#index'
  post '/callback' => 'linebot#callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_user.rb
class LineUser < ApplicationRecord
  validates :line_id, presence: true
  belongs_to :user

  def self.get_token(params)
    uri = URI.parse('https://api.line.me/oauth2/v2.1/token')
    res = Net::HTTP.post_form(uri, { 
      client_id: ENV["LINE_CLIENT_ID"],
      client_secret: ENV["LINE_CLIENT_SECRET"],
      code: params[:code],
      grant_type: "authorization_code",
      redirect_uri: ENV["RIDIRECT_URI"]
    })
    result = JSON.parse(res.body)
    token = result["access_token"]
  end

  def self.user_info(token)
    uri2 = URI.parse("https://api.line.me/v2/profile")
    http = Net::HTTP.new(uri2.host, uri2.port)
    http.use_ssl = uri2.scheme === "https"
    headers = { Authorization: "Bearer #{token}" }
    response = http.get(uri2.path, headers)
    user = JSON.parse(response.body)
  end
  
end

app/models/topic.rb
class Topic < ApplicationRecord

  validates :user_id, presence: true
  validates :send_message, presence: true, length: { maximum: 150 }
  validates :receive_message, presence: true, length: { maximum: 150 }

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/tpic.rb
class Tpic < ApplicationRecord
  validates :user_id, presence: true
  validates :send_message, presence: true, length: { maximum: 150 }
  validates :receive_message, presence: true, length: { maximum: 150 }

  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, uniqueness: true, format: { with:/\A\S+@\S+\.\S+\z/ }
  validates :password, presence: true, confirmation: true, length: { in: 8..32 }, format: { with:/(?=.*?[a-zA-Z])(?=.*?\d)[\w]/ },
              allow_nil: true

  has_secure_password
  has_many :topics, dependent: :destroy
  has_one :line_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  helper_method :current_user, :logged_in?, :log_in, :logged_in_user

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end

  def current_user
    # 一度取得していればその値を検索しないで使う
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/line_users_controller.rb
class LineUsersController < ApplicationController

  def index
     #アクセストークンの取得
    token = LineUser.get_token(params)
    
    #ユーザー情報の取得
    user = LineUser.user_info(token)
    user_line_id = user["userId"]

    #ユーザーとline_uidを紐ずける
    if LineUser.find_by(line_id: user_line_id).nil?
      LineUser.create!(user_id: current_user.id, line_id: user_line_id)
    else
      redirect_to user_path(current_user), info: 'もう連携済みだよ！登録している別のアカウントがあるかも！'
    end
  end

end

app/controllers/linebot_controller.rb
class LinebotController < ApplicationController
  require 'line/bot'

  # callbackアクションのCSRFトークン認証を無効
  protect_from_forgery :except => [:callback]

  def callback
    body = request.body.read

    signature = request.env['HTTP_X_LINE_SIGNATURE']
    unless client.validate_signature(body, signature)
      head :bad_request
    end

    events = client.parse_events_from(body)
    
    events.each { |event|
      #userId取得
    userId = event['source']['userId']
      case event
        # メッセージが送信された場合の対応
      when Line::Bot::Event::Message
        case event.type
          # テキスト形式のメッセージが送られて来た時
        when Line::Bot::Event::MessageType::Text
            # event.message['text']: ユーザーが入力したメッセージ
          input = event.message['text']
          user = LineUser.find_by(line_id: userId)
          topics = user.user.topics
          #送られてきたメッセージをユーザーtopicsから検索
          topic = topics.find_by(send_message: input)
          
          if user.nil?
            push = "まだ連携が終わってないみたい＞＜\nログインして連携させてね！\nhttps://line-botkun.herokuapp.com"

          elsif input == "とうろく"
            push = "https://line-botkun.herokuapp.com"
    
          elsif topic.nil?
            push = input + "？\n『とうろく』で登録画面に飛べるよ！"
          
          elsif input == topic.send_message
            receive_message = topics.find_by(send_message: input).receive_message
            push = receive_message

          else
            push = "もう一度入力してね！"
          end
        end

          #送信するメッセージを定義
        message = {
          type: 'text',
          text: push
        }
        client.reply_message(event['replyToken'], message)
      end
    }
    head :ok
  end

  private
  def client
    @client ||= Line::Bot::Client.new { |config|
      config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
      config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
      }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(session_params)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_path(current_user), success: 'ログインしました'
    else
      flash.now[:danger] = 'ログイン出来ませんでした'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

private

  def session_params
    params.require(:session).permit(:name, :email)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic_id, only: [:edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]
  
  def new
    @topic = Topic.new
  end

  def create
    topic = current_user.topics.new(topic_params)
    if topic.save
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update_attributes(topic_params)
      redirect_to user_path(current_user), success: '編集しました'
    else
      render :edit
    end
  end

  def destroy
    if @topic.user_id == current_user.id
      @topic.destroy
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = "削除出来ません"
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:send_message, :receive_message)
  end

  def set_topic_id
    @topic = Topic.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :show, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in user
      redirect_to user_path(current_user) , success: '登録が完了しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(current_user), success: '編集しました'
    else
      render :edit
    end

  end


  private

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


  # beforeアクション

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_users_helper.rb
module LineUsersHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row top-hero-wrapper text-center pt-5">
  <h2 class="col-xs-6 col-lg-12">LINEbotくん</h2>
  <p class="pb-3 col-xs-6 col-lg-12">LINEの自動返信を設定できるアプリです。</p>
  <div class="center-block col-xs-6 col-lg-12">
    <%= link_to "始める", new_user_path, class: "btn btn-outline-info mb-3" %>
  </div>
  <div class="center-block col-xs-6 col-lg-12">
    <%= link_to "ログイン", login_path, class: "btn btn-outline-danger mb-3" %>
  </div>
</div>

app/views/home/show.html.erb
<p class="">完了しました！</p>
    <%= link_to "戻る", line_path, method: :post, class: "btn btn-outline-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Linebot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top-bg">
      <div class="container p-5">
        <div class="container top-hero-container bg-white">
        <%= render 'shared/header' %>
          <% flash.each do |key, value| %>
            <!--<div class="alert alert-<%= key %>" role="alert"><%= value %></div> -->
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>

            <script>
              $(function(){
                $(".alert").fadeOut(3000);
              });
            </script>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/line_users/index.html.erb
<div class="m-3">
  <p class="pb-3">完了しました！</p>
    <%= link_to "戻る", user_path(current_user), class: "btn btn-outline-success" %>
</div>
  

app/views/shared/_addform.erb
<div class="add shadow p-3 mt-5">
    <% if current_user.line_user.nil? %>
      <p>最初にLineと連携させてね！</p>
        <%= link_to "LINE", "https://access.line.me/oauth2/v2.1/authorize?response_type=code&client_id=" + ENV["LINE_CLIENT_ID"] + "&redirect_uri=" + ENV["RIDIRECT_URI"] + "&state=#{SecureRandom.hex(10)}&scope=profile%20openid",
          class: "btn btn-outline-success mb-3" %>

    <% else %>
      <p>ここから登録できるよ〜</p>
      <%= form_with scope: :topic, url: topics_path, local: true do |f| %>

      <%= f.label :送信, for: 'send', class: 'rounded-pill p-2 send-label form-1'%>
      <%= f.text_field :send_message, id: 'send', class: 'form-1'%>

      <%= f.label :受信, for: 'receive', class: 'rounded-pill p-2 receive-label form-2'%>
      <%= f.text_field :receive_message, id: 'receive', class: 'form-2'%>

      <%= f.submit "登録！", class: 'btn btn-outline-info'%>
      <% end %>
    <div class="QR text-right">
      <div class="line-it-button" data-lang="ja" data-type="friend" data-lineid="@015gtvvt" style="display: none;"></div>
      <script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
      <%= image_tag "linebot.png", size: '100x100' %>
    </div>

    <% end %>
  </div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "title", root_path, class: "navbar-brand" %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <% if logged_in? %>
          <%= link_to user_path(current_user), class: "nav-item nav-link" do %>
            一覧
          <% end %>
          <%= link_to new_topic_path, class: "nav-item nav-link" do %>
            登録
          <% end %>
          <%= link_to edit_user_path(current_user), model: @user, class: "nav-item nav-link" do %>
            ユーザー編集
          <% end %>
          <%= link_to logout_path, method: :delete, class: "nav-item nav-link" do %>
            ログアウト
          <% end %>
        <% else %>
          <%= link_to new_user_path, class: "nav-item nav-link" do %>
            新規登録
          <% end %>
          <%= link_to login_path, class: "nav-item nav-link" do %>
            ログイン
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/topics/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-offset-4 col-md-4">
        <h1 class="title">Change</h1>
        <%= form_with model: @topic, url: topic_path, local: true do |f| %>

          <%= f.label :送信, for: 'send' %>
          <%= f.text_area :send_message, class: 'form-control form-group', id: 'send'%>

          <%= f.label :受信, for: 'receive' %>
          <%= f.text_area :receive_message, class: 'form-control form-group', id: 'receive' %>

          <%= f.submit "変更", class: 'btn btn-outline-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-offset-4 col-md-4">
        <h1 class="title">add</h1>
        <%= form_with model: @topic, url: topics_path, local: true do |f| %>

          <%= f.label :送信, for: 'send'%>
          <%= f.text_field :send_message, class: 'form-control form-group', id: 'send' %>

          <%= f.label :受信, for: 'receive'%>
          <%= f.text_field :receive_message, class: 'form-control form-group', id: 'receive' %>

          <%= f.submit "登録", class: 'btn btn-outline-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-offset-4 col-md-4">
        <h1 class="title">Edit</h1>
        <%= form_with model: @user, url: user_path(current_user), local: true do |f| %>

          <%= f.label :名前, for: 'name' %>
          <%= f.text_field :name, class: 'form-control form-group', id: 'name' %>

          <%= f.label :メールアドレス, for: 'email' %>
          <%= f.text_field :email, class: 'form-control form-group', id: 'email' %>

          <%= f.label :パスワード, for: 'password' %>
          <%= f.password_field :password, class: 'form-control form-group', id: 'password' %>

          <%= f.label :パスワード（確認）, for: 'password_confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control form-group', id: 'password_confirmation' %>

          <%= f.submit "登録", class: 'btn btn-outline-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-offset-4 col-md-4">
        <h1 class="title">Sign up</h1>
        <%= form_with model: @user, url: signup_path, local: true do |f| %>

          <%= f.label :名前, for: 'name' %>
          <%= f.text_field :name, class: 'form-control form-group', id: 'name' %>

          <%= f.label :メールアドレス, for: 'email' %>
          <%= f.text_field :email, class: 'form-control form-group', id: 'email' %>

          <%= f.label :パスワード, for: 'password' %>
          <%= f.password_field :password, class: 'form-control form-group', id: 'password' %>

          <%= f.label :パスワード（確認）, for: 'password_confirmation'%>
          <%= f.password_field :password_confirmation, class: 'form-control form-group', id: 'password_confirmation' %>

          <%= f.submit "登録", class: 'btn btn-outline-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="line-bc">
    <%= render 'shared/addform' %>
    <h2 class="list-title pt-5">List</h2>
    <% @user.topics.each do |topic| %>
      <div class="row">
        <div class="message p-2">
          <div class="send_message rounded-pill p-2 float-left">
            <%= topic.send_message %>
          </div>

          <div class="receive_message rounded-pill p-2 float-left">
            <%= topic.receive_message %>
          </div>

          <div class="option float-right ">
            <%= link_to topic, method: :delete do %>
              <%= fa_icon("trash") %>
            <% end %>
            <%= link_to edit_topic_path(topic.id), modle: @topic do %>
              <%= fa_icon("edit") %>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>